### ISSUE TITLE
[Gamemode]: 玩家加入服务器时加载失败

### ISSUE THREAD

**Issue by MrPiperdine** [AnzhiZhang/MCDReforgedPlugins#114]
首次加载插件时和玩家进入服务器时报错，!!spec无反应

![(U4DI4G`PEH122{I8VHXHRN](https://user-images.githubusercontent.com/128112694/225803240-bfedff18-5c5c-4ac9-be21-5321ec915ced.png)

![_H{_D`46SBSKRJN`$EEBGPI](https://user-images.githubusercontent.com/128112694/225804680-839138c3-32b6-4160-a6cc-1beb964a4d06.png)

系统：Windows  10.0.22621.1413
服务端：fabric-server-mc.1.18.2-loader.0.14.17-launcher.0.11.2 未添加mod
Python版本：v3.11.1:a7a450f
Java版本：17.0.6 x86_64
MCDR版本：2.7.2
依赖：
![image](https://user-images.githubusercontent.com/128112694/225805842-5b8d2735-f96d-4c9d-90c9-f970aaaf2798.png)
已加载插件：
![@0%RL6{RB@QWG 1EBI7AI2C](https://user-images.githubusercontent.com/128112694/225806864-c1340013-4450-4f19-a08b-f7a6b4f7d0f3.png)

**Comment by AnzhiZhang** [comment]
这是由于 MCDR 进行了破坏性的 API 更改，不再自动创建空配置文件导致的
