### ISSUE TITLE
QQchat机器人 由于未启用 RCON，没有返回结果

### ISSUE THREAD

**Issue by LinAnSalA** [AnzhiZhang/MCDReforgedPlugins#117]
请问我应该在哪里启用相关的rcon
服务端的rcon已经开启了
qq执行命令有效果
但是不能返回结果

**Comment by AnzhiZhang** [comment]
https://mcdreforged.readthedocs.io/zh_CN/latest/configuration.html#rcon
下次请发discussion

**Comment by LinAnSalA** [comment]
好的 抱歉 我并不熟悉github
