### ISSUE TITLE
[bot]: Feature: tag功能

### ISSUE THREAD

**Issue by Flash-Z** [AnzhiZhang/MCDReforgedPlugins#119]
## Description丨描述
添加假人tag功能，服务器假人过多的时候使用tag便于查找，例如!!bot list <tag>, 更进一步的话希望能有个tag菜单的功能，列出所有tag，然后自行选择

**Comment by Flash-Z** [comment]
或者直接检索查看是否匹配name 和 comment里面的关键词

**Comment by AnzhiZhang** [comment]
有规划做分类，具体功能设计还需考量

**Comment by Flash-Z** [comment]
> 有规划做分类，具体功能设计还需考量

carpet那个主菜单我觉得挺好

**Comment by AnzhiZhang** [comment]
设计：可以为假人设置 tag，允许设置多个 tag，增加指令按 tag 筛选假人，以及批量操作同一个 tag 的假人
