### ISSUE TITLE
[QQAPI | Feature Request]: Websocket mode support

### ISSUE THREAD

**Issue by alex3236** [AnzhiZhang/MCDReforgedPlugins#127]
The websocket mode is more stable, at least for go-cqhttp. In HTTP mode, inexplicable problems often occur when the settings are correct. This is not a QQAPI problem, but adding ws mode is good for everyone ;)

**Comment by AnzhiZhang** [comment]
Thanks for your issue, there will be an update about websocket support to connect QQAPI directly. But update with QQBridge may be later.

**Comment by lostegoist** [comment]
### http连接时,go-cqhttp后台反复刷屏"上报Event数据到 '反向http post地址'  失败"
抱歉，我遇到上述问题。根据文档的配置，http通信地址对应了'api_host'，而反向http post地址对应了'post_host'。配合QQChat插件，qq机器人能一定程度和mc通信（help和绑定白名单指令能正常工作，能从MC发消息到QQ，而QQ不能发消息到MC）。
但是go-cqhttp的控制台一直反复报错：
![dss (2)](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/67431043/40661c25-962d-4624-b24c-1e80cb820f09)

抱歉，我不是很理解插件和go-cqhttp的工作原理，实在不清楚报错原因。网上案例好像很少，没有找到解决方案。

下面是服务端信息：
- MCDR版本: 2.9.0
- QQAPI版本:1.2.1
- QQChat版本:2.0.0
- mc服务端:1.20 Fabric
- go-cqhttp版本:1.0.0

**Comment by AnzhiZhang** [comment]
@lostegoist 请单独开启issue并提供详细配置信息，或在群内寻求帮助

**Comment by AnzhiZhang** [comment]
将在 1.3.0 发布相关功能
