### ISSUE TITLE
[QQChat] 消息转发相关功能无法正常工作

### ISSUE THREAD

**Issue by lostegoist** [AnzhiZhang/MCDReforgedPlugins#130]
### http连接时,go-cqhttp后台反复刷屏"上报Event数据到 '反向http post地址'  失败"
抱歉，我遇到上述问题。根据文档的配置，http通信地址对应了'api_host'，而反向http post地址对应了'post_host'。配合QQChat插件，qq机器人能一定程度和mc通信（help和绑定白名单指令能正常工作，能从MC发消息到QQ，而QQ不能发消息到MC）。
但是go-cqhttp的控制台一直反复报错：
![dss (2)](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/67431043/40661c25-962d-4624-b24c-1e80cb820f09)

抱歉，我不是很理解插件和go-cqhttp的工作原理，实在不清楚报错原因。网上案例好像很少，没有找到解决方案。

下面是服务端信息：
- MCDR版本: 2.9.0
- QQAPI版本:1.2.1
- QQChat版本:2.0.0
- mc服务端:1.20 Fabric
- go-cqhttp版本:1.0.0
- go-cqhttp选择的连接方式 http

go-cqhttp / config.yml ：
  - http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      version: 11     # OneBot协议版本, 支持 11/12
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
      - url: http://127.0.0.1:5701             # 地址

qq_api / config.json ：
{
    "api_host": "127.0.0.1",
    "api_port": 5700,
    "post_host": "127.0.0.1",
    "post_port": 5701
}

go-cqhttp控制台警告消息刷屏 ：
    [WARNING] : 上报 Event 数据到 http://127.0.0.1:5701 失败：Post "http://127.0.0.1:5701": EOF 将进行第 1 次重试
    [WARNING] : 上报 Event 数据到 http://127.0.0.1:5701 失败：Post "http://127.0.0.1:5701": EOF 将进行第 1 次重试
....

**Comment by lostegoist** [comment]
/help 指令正常
/bound 正常绑定白名单
!!qq 可以正常把消息从MC发送到QQ；但是/mc 没有用，无法从qq发送消息到MC。

**Comment by AnzhiZhang** [comment]
那通信这块应该是正常的，EOF这个只是正常抽风
检查一下qqchat配置文件，mc指令是否已经打开

**Comment by AnzhiZhang** [comment]
另外如果没绑定使用/mc 指令是否有提示？

**Comment by AnzhiZhang** [comment]
群号配置是否正确？请注意主群只能有一个

**Comment by CleMooling** [comment]
![bb485118096908f824be0d34e69ad999](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/93636342/cb2f9e83-e33f-48ff-92d4-c84498441d25)
试试这个gocq配置

**Comment by lostegoist** [comment]
还是一样的，/mc指令无效。

**Comment by CleMooling** [comment]
配置文件启用了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月18日(周日) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AnzhiZhang/MCDReforgedPlugins] [QQChat] 消息转发相关功能无法正常工作 (Issue #130)




 
还是一样的，/mc指令无效。

**Comment by CleMooling** [comment]
> 还是一样的，/mc指令无效。

你看看gocq后台有没有风控提示

**Comment by lostegoist** [comment]
> 你看看gocq后台有没有风控提示
后台倒是没有“风控”提示，但是数据上报失败的警告还是有。

**Comment by Aimerny** [comment]
> 还是一样的，/mc指令无效。
排查建议
1. 确定已打开qq_to_mc的forwards
2. 将聊天的群组已经配置为main_group
3. 在使用/mc之前先使用/bound指令绑定

> 如果未解决，尝试将群组配置到sync群中测试不使用mc指令发送到服务器时功能是否正常
