### ISSUE TITLE
[QQChat | Bug] 配置项server_name疑似无效

### ISSUE THREAD

**Issue by lostegoist** [AnzhiZhang/MCDReforgedPlugins#132]
在QQChat插件中，其配置文件config.json中默认没有server_name配置项。根据说明，或许是能添加server_name配置项，但是添加之后启动服务器会直接直接重置config.json文件。导致需要重新配置插件。以下是详细信息。
修改config为以下格式：
> {
    "main_group": [
        XXXXXXX
    ],
    "manage_groups": [
    ],
    "message_sync_groups": [
    ],
    "server_name": 'someServerName',  //此行 为手动添加项
    "admins": [
        XXXXXXX
    ],
......

保存退出并重载服务器(完全重启)后，config.json重置变回默认格式。
抱歉，我不是很懂插件的运作方式，如有勘误请指教。(っ◞‸◟c)

**Comment by Aimerny** [comment]
bug，下个版本修掉

**Comment by CleMooling** [comment]
> 在QQChat插件中，其配置文件config.json中默认没有server_name配置项。根据说明，或许是能添加server_name配置项，但是添加之后启动服务器会直接直接重置config.json文件。导致需要重新配置插件。以下是详细信息。 修改config为以下格式：
> 
> > {
> > "main_group": [
> > XXXXXXX
> > ],
> > "manage_groups": [
> > ],
> > "message_sync_groups": [
> > ],
> > "server_name": 'someServerName',  //此行 为手动添加项
> > "admins": [
> > XXXXXXX
> > ],
> > ......
> 
> 保存退出并重载服务器(完全重启)后，config.json重置变回默认格式。 抱歉，我不是很懂插件的运作方式，如有勘误请指教。(っ◞‸◟c)

有个临时的解决方案是在插件源码里面直接修改。也可以同时自定义聊天转发等语句。

**Comment by lostegoist** [comment]
> 有个临时的解决方案是在插件源码里面直接修改。也可以同时自定义聊天转发等语句。

是的，我之后便是直接在源码里找到了该项，顺便把其他的文本修改为了个性化文本。

**Comment by Aimerny** [comment]
> > 在QQChat插件中，其配置文件config.json中默认没有server_name配置项。根据说明，或许是能添加server_name配置项，但是添加之后启动服务器会直接直接重置config.json文件。导致需要重新配置插件。以下是详细信息。 修改config为以下格式：
> > > {
> > > "main_group": [
> > > XXXXXXX
> > > ],
> > > "manage_groups": [
> > > ],
> > > "message_sync_groups": [
> > > ],
> > > "server_name": 'someServerName',  //此行 为手动添加项
> > > "admins": [
> > > XXXXXXX
> > > ],
> > > ......
> > 
> > 
> > 保存退出并重载服务器(完全重启)后，config.json重置变回默认格式。 抱歉，我不是很懂插件的运作方式，如有勘误请指教。(っ◞‸◟c)
> 
> 有个临时的解决方案是在插件源码里面直接修改。也可以同时自定义聊天转发等语句。

在上次更新的时候server_name的配置有问题，会在issue关联的pr中修复，自定义聊天转发目前暂无计划支持，请自行斟酌更改
