### ISSUE TITLE
[QQChat]群聊内命令/list返回信息有误

### ISSUE THREAD

**Issue by CleMooling** [AnzhiZhang/MCDReforgedPlugins#135]
在群聊内使用/list时，返回的玩家名单是开服以来登录过的玩家的名单而非实际在线名单。如图所示：
![-42ff2d79c011dc93](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/93636342/3dc0b04e-62b8-4db0-85a8-f7ff7e7f961c)
插件和依赖都是最新版，服务端是Paper系。

**Comment by CleMooling** [comment]
稳定复现办法：
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/93636342/715fa1b3-6393-43e4-9720-68e201afcca6)

**Comment by Aimerny** [comment]
> 在群聊内使用/list时，返回的玩家名单是开服以来登录过的玩家的名单而非实际在线名单。如图所示： ![-42ff2d79c011dc93](https://user-images.githubusercontent.com/93636342/246654941-3dc0b04e-62b8-4db0-85a8-f7ff7e7f961c.png) 插件和依赖都是最新版，服务端是Paper系。

1. 确定一下MCDR的handler是否选择正确
2. 看到case场景貌似是使用geyser连接入服务器的玩家出现的，请确定不通过geyser进入的玩家是否也有这个问题

**Comment by AnzhiZhang** [comment]
> 稳定复现办法：

@CleMooling 稳定复现指的是开发者可以在开发者的设备和环境上复现，不是你有个截图……

**Comment by AnzhiZhang** [comment]
高度怀疑 handler 有问题导致了识别了玩家进入，但没有识别到玩家离开

**Comment by CleMooling** [comment]
明天我提供一下handler信息和服务端以及mcdr的详细信息



---原始邮件---
发件人: "Andy ***@***.***&gt;
发送时间: 2023年6月18日(周日) 晚上11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AnzhiZhang/MCDReforgedPlugins] [QQChat]群聊内命令/list返回信息有误 (Issue #135)




 
高度怀疑 handler 有问题导致了识别了玩家进入，但没有识别到玩家离开

**Comment by AnzhiZhang** [comment]
如果没有进一步回复将在三天后关闭
