### ISSUE TITLE
[QQChat] Feature: 新功能建议

### ISSUE THREAD

**Issue by CleMooling** [AnzhiZhang/MCDReforgedPlugins#139]
希望增加以下提示信息的转发功能：
1. 玩家上下线消息
2. 玩家成就/进度达成通知
3. 玩家死亡时提示

**Comment by Aimerny** [comment]
> 希望增加以下提示信息的转发功能：
> 
> 1. 玩家上下线消息
> 2. 玩家成就/进度达成通知
> 3. 玩家死亡时提示

1. 将会有计划排期支持
2. 过于定制化并且意义不大，不考虑支持
3. MCDR目前没有玩家死亡事件，暂无计划支持

**Comment by AnzhiZhang** [comment]
参见 #138
