### ISSUE TITLE
[Bot]: Feature：自动更新

### ISSUE THREAD

**Issue by AnzhiZhang** [AnzhiZhang/MCDReforgedPlugins#143]
## Description丨描述
假人下线时自动更新位置维度等信息，这样上线时可以按照下线的位置，同时模拟原版行为，用于世吞等需要假人移动的机器。现在计划把这个功能做一个设置，可以选择每个假人是否自动更新。
征求两个意见：
1.这个功能默认开启还是关闭？还是在配置文件中设置这个设置的默认值？
2.这个功能应该做 True/False 设置还是 list 设置，即全部更新或更新部分内容（位置、方向、维度）
![28%$F%OQ0(12` GVPJY X63](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/37402126/4efa0210-52cd-495a-b700-3818f669c4d2)

**Comment by Aimerny** [comment]
> ## Description丨描述
> 假人下线时自动更新位置维度等信息，这样上线时可以按照下线的位置，同时模拟原版行为，用于世吞等需要假人移动的机器。现在计划把这个功能做一个设置，可以选择每个假人是否自动更新。 征求两个意见： 1.这个功能默认开启还是关闭？还是在配置文件中设置这个设置的默认值？ 2.这个功能应该做 True/False 设置还是 list 设置，即全部更新或更新部分内容（位置、方向、维度） ![28%$F%OQ0(12` GVPJY X63](https://user-images.githubusercontent.com/37402126/255377593-4efa0210-52cd-495a-b700-3818f669c4d2.png)

1. 默认关闭，同时建议新增加一个更新的字段，不要覆盖掉初次保存时的信息。防止玩家故意或无意移动假人并使其下线后，变相实现del->save操作。
2. 感觉True/False的粒度已经足够，目前没想象到需要分离控制的场景
