### ISSUE TITLE
MCDR 插件对外接口 API

### ISSUE THREAD

**Issue by AnzhiZhang** [AnzhiZhang/MCDReforgedPlugins#146]
为方便其他服务通过接口与 MCDR 插件交互，计划发布一个 API 插件，提供 HTTP 的接口能力，其它插件可以注册对外提供的接口。 

在某技术大佬的敦促下，决定框架选型 fastapi

现在下方征求该插件命名

_Originally posted by @AnzhiZhang in https://github.com/AnzhiZhang/MCDReforgedPlugins/issues/145#issuecomment-1657181013_

**Comment by AnzhiZhang** [comment]
@alex3236 fastapi

**Comment by xjh2009** [comment]
WSDR
