### ISSUE TITLE
个别玩家!!spec失效

### ISSUE THREAD

**Issue by starhush** [AnzhiZhang/MCDReforgedPlugins#147]
情景：我使用!!spec后因聊天验证被t出服务器，再次进入发现自己模式变成了冒险，我又再次输入!!spec又因同样原因被踢出，可这次进入模式并没有改为生存，还是冒险模式。之后我大退（重启游戏）没有出现聊天框一打字就被t出的情况，但是却发现!!spec对我无效了，我不管怎么使用都无法切换模式
![5941e66f430b4b4c7ac009a8bd4fc9a4](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/132283814/d8322f2f-e0c3-4e8d-b668-b68f880e36df)
其他人可以正常使用，就我无法正常使用，服务器后台输出如下：
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/132283814/67b16737-7ed5-4312-83f3-012849e7ced3)
以下是服务器其他玩家正常使用图片及服务器后台输出
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/132283814/613efc6f-d5fe-4e6a-9a4f-e52f716d70db)
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/132283814/3126f03b-f195-46fd-9760-198e1a624790)
最后我还把出现问题的日志也要来了
[日志.zip](https://github.com/AnzhiZhang/MCDReforgedPlugins/files/12448564/default.zip)

**Comment by starhush** [comment]
还有只要一退服务器再重新进入就是观察者模式，就算退服时是生存模式，重新进服就是观察者

**Comment by AnzhiZhang** [comment]
可以尝试自行修改数据文件并重载插件修复

**Comment by starhush** [comment]
> 

数据文件在什么位置呢，重载插件没有用，难受

**Comment by AnzhiZhang** [comment]
> > 
> 
> 数据文件在什么位置呢，重载插件没有用，难受

文件在 `config/bot` 中，如不会修改可以在没有玩家进入旁观时直接删除整个文件，然后重载插件或重启

**Comment by starhush** [comment]
> > > 
> > 
> > 
> > 数据文件在什么位置呢，重载插件没有用，难受
> 
> 文件在 中，如不会修改可以在没有玩家进入旁观时直接删除整个文件，然后重载插件或重启`config/bot`
在服务器全体玩家都是生存模式下我删除了处于config内的插件配置文件
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/132283814/d323bf76-7107-46a5-8b21-91d0257d0514)
并且重启了服务器发现问题解决了
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/132283814/88b13956-ff11-4e8a-a9b0-4c808190f09d)
感谢你的耐心解答，谢谢

**Comment by starhush** [comment]
> > > 
> > 
> > 
> > 数据文件在什么位置呢，重载插件没有用，难受
> 
> 文件在 中，如不会修改可以在没有玩家进入旁观时直接删除整个文件，然后重载插件或重启`config/bot`

谢谢，按照你的步骤问题已经解决，再次感谢你如此耐心解答。
确实要全体玩家处于生存模式下删除配置文件重启才可以，第一次我自己是在观察者模式下所以导致无效
最后再次感谢，谢谢您

**Comment by AnzhiZhang** [comment]
可能是服务器卡顿或异常重启、玩家改名、手动切换模式等导致的问题，在不便排查的情况下这是最简单的修复方式了。未来注意避免即可
