### ISSUE TITLE
[bug]: 错误的参数分割

### ISSUE THREAD

**Issue by mcxiaochenn** [AnzhiZhang/MCDReforgedPlugins#165]
## Description丨描述
使用save保存假人位置和朝向时/!!bot save sleep 1698.5 70 -644.5 -90 0 朝向不能被正确保存

## Screenshots丨截图

![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/130777336/98921556-e001-4be8-9bf9-37fe70613cd3)

## Additional context丨附加信息
CY 如果修复了请dd my qq：1684643711

**Comment by AnzhiZhang** [comment]
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/37402126/05132250-ea01-41f2-9e3e-6d57d0b57ad9)
没有问题

**Comment by AnzhiZhang** [comment]
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/37402126/307b1a7c-3877-4721-bca0-a1faa2387496)
玩家执行也没有问题
