### ISSUE TITLE
[QQ API] New Protocols

### ISSUE THREAD

**Issue by Evander0** [AnzhiZhang/MCDReforgedPlugins#185]
go-cqhttp已经停止支持且无法稳定使用，是否考虑添加对chronocat的支持？（使用Satori或RedProtocol）

**Comment by AnzhiZhang** [comment]
暂时不考虑，欢迎 PR。腾讯目前已经推出官方机器人且支持群组，计划观望一段时间稳定后支持官方机器人

**Comment by haohao927** [comment]
是否考虑兼容一下 onebot 协议？有个项目就是基于了官方 qqbot 的 api 然后兼容 onebot 协议的，[https://github.com/Hoshinonyaruko/Gensokyo](url)
如果支持 onebot 协议的话那就可以连接不仅仅是 Gensokyo 亦或是其他项目（比如 Lagrange 或者是 OpenShamrock 等目前较为稳定）。因为官方的 qq 机器人确实是不用担心稳定性问题，但是对于个人开发者的限制较大。

**Comment by AnzhiZhang** [comment]
> 是否考虑兼容一下 onebot 协议？有个项目就是基于了官方 qqbot 的 api 然后兼容 onebot 协议的，[https://github.com/Hoshinonyaruko/Gensokyo](url) 如果支持 onebot 协议的话那就可以连接不仅仅是 Gensokyo 亦或是其他项目（比如 Lagrange 或者是 OpenShamrock 等目前较为稳定）。因为官方的 qq 机器人确实是不用担心稳定性问题，但是对于个人开发者的限制较大。

该项目就是使用的onebot协议

**Comment by Evander0** [comment]
> > 是否考虑兼容一下 onebot 协议？有个项目就是基于了官方 qqbot 的 api 然后兼容 onebot 协议的，[https://github.com/Hoshinonyaruko/Gensokyo](url) 如果支持 onebot 协议的话那就可以连接不仅仅是 Gensokyo 亦或是其他项目（比如 Lagrange 或者是 OpenShamrock 等目前较为稳定）。因为官方的 qq 机器人确实是不用担心稳定性问题，但是对于个人开发者的限制较大。
> 
> 该项目就是使用的onebot协议

现在项目使用的似乎是反向ws，考虑支持一下正向ws吗？

**Comment by AnzhiZhang** [comment]
> > > 是否考虑兼容一下 onebot 协议？有个项目就是基于了官方 qqbot 的 api 然后兼容 onebot 协议的，[https://github.com/Hoshinonyaruko/Gensokyo](url) 如果支持 onebot 协议的话那就可以连接不仅仅是 Gensokyo 亦或是其他项目（比如 Lagrange 或者是 OpenShamrock 等目前较为稳定）。因为官方的 qq 机器人确实是不用担心稳定性问题，但是对于个人开发者的限制较大。
> > 
> > 
> > 该项目就是使用的onebot协议
> 
> 现在项目使用的似乎是反向ws，考虑支持一下正向ws吗？

不考虑

**Comment by AnzhiZhang** [comment]
等待官方开放个人的群组机器人权限

**Comment by duncai233** [comment]
是否考虑一下正向ws，部分场景无法使用反向

**Comment by AnzhiZhang** [comment]
> 是否考虑一下正向ws，部分场景无法使用反向

可以的

**Comment by duncai233** [comment]
是否能尽快更新

**Comment by AnzhiZhang** [comment]
> 是否能尽快更新

PR is welcomed

**Comment by AnzhiZhang** [comment]
移至 #223
