### ISSUE TITLE
假人插件首次召唤出的假人是创造模式

### ISSUE THREAD

**Issue by zhaixianyu** [AnzhiZhang/MCDReforgedPlugins#186]
假人插件首次召唤出的假人是创造模式
插件版本1.1.2/1.0.6 游戏版本1.20.4
配置中是生存模式。
再次召唤假人后能看到设置为生存模式的提示
这似乎是游戏版本的问题 我在1.18.2没有遇到这个情况

**Comment by AnzhiZhang** [comment]
不是大问题。猜测是因为如果先保存了假人，没有召唤过，第一次召唤时由于需要联网获取uuid等信息，所以加入会慢一些，导致先执行了设置游戏模式，然后假人才加入游戏，这个可以通过控制台日志验证。

**Comment by zhaixianyu** [comment]
> 不是大问题。猜测是因为如果先保存了假人，没有召唤过，第一次召唤时由于需要联网获取uuid等信息，所以加入会慢一些，导致先执行了设置游戏模式，然后假人才加入游戏，这个可以通过控制台日志验证。

是每次重启服务器后的首次召唤

**Comment by zhaixianyu** [comment]
我尝试过mod仅保留carpet 插件仅保留bot和相关依赖。测试的结果仍是如此

**Comment by zhaixianyu** [comment]
[Server] [00:03:20] [Server thread/INFO]: <zhaixianyu> !!bot list
[Server] [00:03:22] [Server thread/INFO]: <zhaixianyu> !!bot spawn bot_test
[Server] [00:03:22] [Server thread/INFO]: No player was found
[Server] [00:03:22] [Worker-Main-2/INFO]: Bot_Test[local] logged in with entity id 262 at (-3.318348147334423, 119.0, 19.12480753154755)
[Server] [00:03:22] [Worker-Main-2/INFO]: Bot_Test joined the game
[Server] [00:03:25] [Server thread/INFO]: <zhaixianyu> !!bot kill bot_test
[Server] [00:03:25] [Server thread/INFO]: Bot_Test lost connection: Killed
[Server] [00:03:25] [Server thread/INFO]: Bot_Test left the game
[Server] [00:03:26] [Server thread/INFO]: <zhaixianyu> !!bot spawn bot_test
[Server] [00:03:26] [Server thread/INFO]: Bot_Test[local] logged in with entity id 263 at (-3.318348147334423, 119.0, 19.12480753154755)
[Server] [00:03:26] [Server thread/INFO]: Bot_Test joined the game
[Server] [00:03:26] [Server thread/INFO]: Set Bot_Test's game mode to Survival Mode

后台日志是这样的

**Comment by AnzhiZhang** [comment]
确实是假人加入前就使用指令修改了游戏模式，可通过修改插件尝试解决
