### ISSUE TITLE
[Online_Player_API]: Feature 请求：关于校验小写名称的问题

### ISSUE THREAD

**Issue by FlipWind** [AnzhiZhang/MCDReforgedPlugins#188]
## Description丨描述

请求增加一个列表，里面存储玩家名称转换后的小写名，以便更好地方便用户使用。

## Additional context丨附加信息

假设有这样一个 List: [Steve, Alex, SkyW]  的在线玩家列表和 example = "alex"，
我希望  example.lower() in get_player_list 的结果是 True.

**Comment by AnzhiZhang** [comment]
请自行转换，mc的玩家名大小写敏感，有特殊需求请自行处理。不提供对于非标准的支持
