### ISSUE TITLE
gamemode 插件bug 

### ISSUE THREAD

**Issue by MarcoGao123** [AnzhiZhang/MCDReforgedPlugins#191]
![2024-04-29_11 13 45](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/48619664/083d538d-79b7-4454-92b6-4427e0d1ade2)

掠夺者会对使用!!spec进入旁观模式的真人玩家产生仇恨, 并使用弩进行攻击

**Comment by AnzhiZhang** [comment]
使用 gamemode 也一样

**Comment by MarcoGao123** [comment]
原版旁观没仇恨吧 我刚去试了下

**Comment by AnzhiZhang** [comment]
插件用的就是 gamemode
