### ISSUE TITLE
[Bot]: 设置假人自动更新以后无法下线假人

### ISSUE THREAD

**Issue by Aimerny** [AnzhiZhang/MCDReforgedPlugins#193]
**Please go to [discussions](https://github.com/AnzhiZhang/MCDReforgedPlugins/discussions) to ask for help!**

**需要帮助请前往 [discussions](https://github.com/AnzhiZhang/MCDReforgedPlugins/discussions)！**

## Description丨描述

修改了假人bot_a的自动更新字段为True以后无法使用 `!!bot kill bot_a` 以及 `!!bot kill a`来下线假人。修改为False以后正常下线

## Screenshots丨截图
> 修改为自动更新尝试操作下线无效

![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/121629148/8d6575a9-11b8-4d18-bcff-b83dc11f3648)
> 修改回False正常下线，随后重新改回True问题复现

![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/121629148/b179ac52-53b6-4d1d-a1b9-ebdecaf29253)

## Additional context丨附加信息

游戏版本: 1.20.1
bot插件版本: 1.1.4
MCDR版本: 2.12.3

**Comment by Aimerny** [comment]
补充服务端日志报错：
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/121629148/5de44778-950a-4e08-9bbc-020550c25781)

**Comment by AnzhiZhang** [comment]
获取位置失败，请检查Minecraft Data API，并尝试玩家直接spawn是否正常

**Comment by Aimerny** [comment]
> 获取位置失败，请检查Minecraft Data API，并尝试玩家直接spawn是否正常

直接spawn正常，截图上下文中有相关信息

**Comment by AnzhiZhang** [comment]
name 不一致
https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/af051d924b9f333600e66c3fe8608ee82dce28c1/src/bot/bot/bot.py#L226
