### ISSUE TITLE
[bot]: 部分玩家使用一直提示约束未满足

### ISSUE THREAD

**Issue by Realzhazha** [AnzhiZhang/MCDReforgedPlugins#196]
## Description丨描述

部分玩家使用例如 `!!bot save 1`的时候提示约束未满足，服务器后台无信息，因此抱歉无法提供更多信息

## Screenshots丨截图

![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/35806568/14ca5da8-99ae-41c1-9944-eb11430262f6)
![image](https://github.com/AnzhiZhang/MCDReforgedPlugins/assets/35806568/c910b6c5-8106-4576-a0e8-3b969b036bed)

**Comment by AnzhiZhang** [comment]
#195
