### ISSUE TITLE
[AdvancedCalculator]: Requirement not met

### ISSUE THREAD

**Issue by LingEmberMaple** [AnzhiZhang/MCDReforgedPlugins#198]
```
> !!calc
[MCDR] [TaskExecutor/INFO]: Requirement not met: !!calc <--
```

**Comment by AnzhiZhang** [comment]
Why do you need this feature in the console???

**Comment by LingEmberMaple** [comment]
My bad. At first it didn't work in the game, so I tried it in the console. Now it works after the server restarts.
