### ISSUE TITLE
[Bot]: 兼容高版本维度翻译

### ISSUE THREAD

**Issue by jianchihu-leader** [AnzhiZhang/MCDReforgedPlugins#210]
## Description丨描述
在使用bot插件时，假人信息中的维度识别有误
主世界会被识别为create World.customize.preset.overworld
## Screenshots丨截图

<img width="418" alt="f992ad30d5c735e5842a2c99229d602" src="https://github.com/user-attachments/assets/c6a07649-56fc-40ad-994a-67ae409304b4">

## Additional context丨附加信息

末地和地狱的识别是正常的

**Comment by jianchihu-leader** [comment]
服务器未安装任何自定义维度插件

**Comment by AnzhiZhang** [comment]
请提供所有版本信息

**Comment by AnzhiZhang** [comment]
1. https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%88%AB%E5%8A%A8%E8%BE%84%E5%A3%B0%E7%A7%B0%E6%89%BE%E5%88%B0-bug
2. https://github.com/TISUnion/Here/issues/26

**Comment by jianchihu-leader** [comment]
十分抱歉……最近有一些其他事情耽误了回复您

**Comment by jianchihu-leader** [comment]
我使用的MC版本是 1.20.1 原版端+Fabric

**Comment by jianchihu-leader** [comment]
MCDR是1.12.3
