### ISSUE TITLE
[Minecraft Command Register]: 指令注册失败Unknown or incomplete command, see below for error

### ISSUE THREAD

**Issue by mcxiaochenn** [AnzhiZhang/MCDReforgedPlugins#212]
## Description丨描述
[Server] [17:37:33] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [17:37:33] [Server thread/INFO]: mcdr register {"data": [{"name": "!!MCDR", "type": "LITERAL", "children": [{"name": "abort", "type": "LITERAL", "children"
: []}, {"name": "checkupdate", "type": "LITERAL", "children": []}, {"name": "cu", "type": "LITERAL", "children": []}, {"name": "confirm", "type": "LITERAL", "childr
en": []}, {"name": "debug", "type": "LITERAL", "children": [{"name": "thread_dump", "type": "LITERAL", "children": [{"name": "#all", "type": "LITERAL", "children":
[]}, {"name": "thread_name", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "translation", "type": "LITERAL", "children": [{"name": "get", "type": "LITERAL",
"children": [{"name": "translation_key", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "dump", "type": "LITERAL", "children": [{"name": "json_path", "type":
"QUOTABLE_TEXT", "children": []}]}]}, {"name": "command_dump", "type": "LITERAL", "children": [{"name": "all", "type": "LITERAL", "children": []}, {"name": "plugin"
, "type": "LITERAL", "children": [{"name": "plugin_id", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "node", "type": "LITERAL", "children": [{"name": "liter
al_name", "type": "QUOTABLE_TEXT", "children": []}]}]}]}, {"name": "perm", "type": "LITERAL", "children": [{"name": "list", "type": "LITERAL", "children": [{"name":
 "level", "type": "TEXT", "children": []}]}, {"name": "set", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": [{"name": "leve
l", "type": "TEXT", "children": []}]}]}, {"name": "q", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "quer
y", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "remove", "type": "LITERAL", "children": [{"name": "play
er", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "rm", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": []}]}, {"nam
e": "setdefault", "type": "LITERAL", "children": [{"name": "level", "type": "TEXT", "children": []}]}, {"name": "setd", "type": "LITERAL", "children": [{"name": "le
vel", "type": "TEXT", "children": []}]}]}, {"name": "permission", "type": "LITERAL", "children": [{"name": "list", "type": "LITERAL", "children": [{"name": "level",
 "type": "TEXT", "children": []}]}, {"name": "set", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": [{"name": "level", "type
": "TEXT", "children": []}]}]}, {"name": "q", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "query", "type
": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "remove", "type": "LITERAL", "children": [{"name": "player", "typ
e": "QUOTABLE_TEXT", "children": []}]}, {"name": "rm", "type": "LITERAL", "children": [{"name": "player", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "setd
efault", "type": "LITERAL", "children": [{"name": "level", "type": "TEXT", "children": []}]}, {"name": "setd", "type": "LITERAL", "children": [{"name": "level", "ty
pe": "TEXT", "children": []}]}]}, {"name": "plugin", "type": "LITERAL", "children": [{"name": "list", "type": "LITERAL", "children": []}, {"name": "info", "type": "
LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "load", "type": "LITERAL", "children": [{"name": "file_name", "type": "QUOT
ABLE_TEXT", "children": []}]}, {"name": "enable", "type": "LITERAL", "children": [{"name": "file_name", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "reload
", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "unload", "type": "LITERAL", "children": [{"name": "plugin_id",
 "type": "TEXT", "children": []}]}, {"name": "disable", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "reloadall
", "type": "LITERAL", "children": []}, {"name": "ra", "type": "LITERAL", "children": []}, {"name": "browse", "type": "LITERAL", "children": [{"name": "--id", "type"
: "LITERAL", "children": [{"name": "plugin_id", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "-i", "type": "LITERAL", "children": [{"name": "plugin_id", "ty
pe": "QUOTABLE_TEXT", "children": []}]}, {"name": "keyword", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "checkupdate", "type": "LITERAL", "children": [{"n
ame": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "cu", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name
": "install", "type": "LITERAL", "children": [{"name": "--target", "type": "LITERAL", "children": [{"name": "target", "type": "QUOTABLE_TEXT", "children": []}]}, {"
name": "-t", "type": "LITERAL", "children": [{"name": "target", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "-u", "type": "TEXT", "children": []}, {"name":
 "-U", "type": "TEXT", "children": []}, {"name": "--upgrade", "type": "TEXT", "children": []}, {"name": "--dry-run", "type": "TEXT", "children": []}, {"name": "--co
nfirm", "type": "TEXT", "children": []}, {"name": "--yes", "type": "TEXT", "children": []}, {"name": "-y", "type": "TEXT", "children": []}, {"name": "--no-dependenc
ies", "type": "TEXT", "children": []}, {"name": "plugin_specifier", "type": "TEXT", "children": []}]}, {"name": "refreshmeta", "type": "LITERAL", "children": []}]},
 {"name": "plg", "type": "LITERAL", "children": [{"name": "list", "type": "LITERAL", "children": []}, {"name": "info", "type": "LITERAL", "children": [{"name": "plu
gin_id", "type": "TEXT", "children": []}]}, {"name": "load", "type": "LITERAL", "children": [{"name": "file_name", "type": "QUOTABLE_TEXT", "children": []}]}, {"nam
e": "enable", "type": "LITERAL", "children": [{"name": "file_name", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "reload", "type": "LITERAL", "children": [{
"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "unload", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]},
{"name": "disable", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "reloadall", "type": "LITERAL", "children": []
}, {"name": "ra", "type": "LITERAL", "children": []}, {"name": "browse", "type": "LITERAL", "children": [{"name": "--id", "type": "LITERAL", "children": [{"name": "
plugin_id", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "-i", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "QUOTABLE_TEXT", "children": []
}]}, {"name": "keyword", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "checkupdate", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "
children": []}]}, {"name": "cu", "type": "LITERAL", "children": [{"name": "plugin_id", "type": "TEXT", "children": []}]}, {"name": "install", "type": "LITERAL", "ch
ildren": [{"name": "--target", "type": "LITERAL", "children": [{"name": "target", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "-t", "type": "LITERAL", "chi
ldren": [{"name": "target", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "-u", "type": "TEXT", "children": []}, {"name": "-U", "type": "TEXT", "children": [
]}, {"name": "--upgrade", "type": "TEXT", "children": []}, {"name": "--dry-run", "type": "TEXT", "children": []}, {"name": "--confirm", "type": "TEXT", "children":
[]}, {"name": "--yes", "type": "TEXT", "children": []}, {"name": "-y", "type": "TEXT", "children": []}, {"name": "--no-dependencies", "type": "TEXT", "children": []
}, {"name": "plugin_specifier", "type": "TEXT", "children": []}]}, {"name": "refreshmeta", "type": "LITERAL", "children": []}]}, {"name": "pref", "type": "LITERAL",
 "children": [{"name": "list", "type": "LITERAL", "children": []}, {"name": "language", "type": "LITERAL", "children": [{"name": "set", "type": "LITERAL", "children
": [{"name": "value", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "reset", "type": "LITERAL", "children": []}]}]}, {"name": "preference", "type": "LITERAL"
, "children": [{"name": "list", "type": "LITERAL", "children": []}, {"name": "language", "type": "LITERAL", "children": [{"name": "set", "type": "LITERAL", "childre
n": [{"name": "value", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "reset", "type": "LITERAL", "children": []}]}]}, {"name": "reload", "type": "LITERAL", "
children": [{"name": "plugin", "type": "LITERAL", "children": []}, {"name": "plg", "type": "LITERAL", "children": []}, {"name": "cfg", "type": "LITERAL", "children"
: []}, {"name": "config", "type": "LITERAL", "children": []}, {"name": "perm", "type": "LITERAL", "children": []}, {"name": "permission", "type": "LITERAL", "childr
en": []}, {"name": "all", "type": "LITERAL", "children": []}]}, {"name": "r", "type": "LITERAL", "children": [{"name": "plugin", "type": "LITERAL", "children": []},
 {"name": "plg", "type": "LITERAL", "children": []}, {"name": "cfg", "type": "LITERAL", "children": []}, {"name": "config", "type": "LITERAL", "children": []}, {"na
me": "perm", "type": "LITERAL", "children": []}, {"name": "permission", "type": "LITERAL", "children": []}, {"name": "all", "type": "LITERAL", "children": []}]}, {"
name": "server", "type": "LITERAL", "children": [{"name": "start", "type": "LITERAL", "children": []}, {"name": "stop", "type": "LITERAL", "children": []}, {"name":
 "stop_exit", "type": "LITERAL", "children": []}, {"name": "exit", "type": "LITERAL", "children": []}, {"name": "restart", "type": "LITERAL", "children": []}, {"nam
e": "kill", "type": "LITERAL", "children": []}]}, {"name": "status", "type": "LITERAL", "children": []}]}, {"name": "!!help", "type": "LITERAL", "children": [{"name
": "page", "type": "INTEGER", "children": []}]}, {"name": "!!pb", "type": "LITERAL", "children": [{"name": "help", "type": "LITERAL", "children": [{"name": "what",
"type": "TEXT", "children": []}]}, {"name": "make", "type": "LITERAL", "children": [{"name": "comment", "type": "GREEDY_TEXT", "children": []}]}, {"name": "show", "
type": "LITERAL", "children": [{"name": "backup_id", "type": "INTEGER", "children": []}]}, {"name": "rename", "type": "LITERAL", "children": [{"name": "backup_id",
"type": "INTEGER", "children": [{"name": "comment", "type": "GREEDY_TEXT", "children": []}]}]}, {"name": "delete_range", "type": "LITERAL", "children": [{"name": "b
ackup_id_range", "type": "TEXT", "children": []}]}, {"name": "prune", "type": "LITERAL", "children": []}, {"name": "diff", "type": "LITERAL", "children": [{"name":
"backup_id_old", "type": "INTEGER", "children": [{"name": "backup_id_new", "type": "INTEGER", "children": []}]}]}, {"name": "crontab", "type": "LITERAL", "children"
: [{"name": "job_id", "type": "ENUMERATION", "children": [{"name": "pause", "type": "LITERAL", "children": []}, {"name": "resume", "type": "LITERAL", "children": []
}]}]}, {"name": "database", "type": "LITERAL", "children": [{"name": "overview", "type": "LITERAL", "children": []}, {"name": "inspect", "type": "LITERAL", "childre
n": [{"name": "backup", "type": "LITERAL", "children": [{"name": "backup_id", "type": "INTEGER", "children": []}]}, {"name": "file", "type": "LITERAL", "children":
[{"name": "backup_id", "type": "INTEGER", "children": [{"name": "file_path", "type": "QUOTABLE_TEXT", "children": []}]}]}, {"name": "blob", "type": "LITERAL", "chil
dren": [{"name": "blob_hash", "type": "TEXT", "children": []}]}]}, {"name": "validate", "type": "LITERAL", "children": [{"name": "all", "type": "LITERAL", "children
": []}, {"name": "blobs", "type": "LITERAL", "children": []}, {"name": "files", "type": "LITERAL", "children": []}]}, {"name": "vacuum", "type": "LITERAL", "childre
n": []}, {"name": "migrate_compress_method", "type": "LITERAL", "children": [{"name": "compress_method", "type": "ENUMERATION", "children": []}]}, {"name": "migrate
_hash_method", "type": "LITERAL", "children": [{"name": "hash_method", "type": "ENUMERATION", "children": []}]}]}, {"name": "confirm", "type": "LITERAL", "children"
: []}, {"name": "abort", "type": "LITERAL", "children": []}, {"name": "back", "type": "LITERAL", "children": [{"name": "--confirm", "type": "TEXT", "children": []},
 {"name": "--fail-soft", "type": "TEXT", "children": []}, {"name": "--no-verify", "type": "TEXT", "children": []}, {"name": "backup_id", "type": "INTEGER", "childre
n": [{"name": "--confirm", "type": "TEXT", "children": []}, {"name": "--fail-soft", "type": "TEXT", "children": []}, {"name": "--no-verify", "type": "TEXT", "childr
en": []}]}]}, {"name": "delete", "type": "LITERAL", "children": [{"name": "backup_id", "type": "TEXT", "children": []}]}, {"name": "export", "type": "LITERAL", "chi
ldren": [{"name": "backup_id", "type": "INTEGER", "children": [{"name": "--fail-soft", "type": "TEXT", "children": []}, {"name": "--no-verify", "type": "TEXT", "chi
ldren": []}, {"name": "--overwrite", "type": "TEXT", "children": []}, {"name": "--no-meta", "type": "TEXT", "children": []}, {"name": "export_format", "type": "ENUM
ERATION", "children": [{"name": "--fail-soft", "type": "TEXT", "children": []}, {"name": "--no-verify", "type": "TEXT", "children": []}, {"name": "--overwrite", "ty
pe": "TEXT", "children": []}, {"name": "--no-meta", "type": "TEXT", "children": []}]}]}]}, {"name": "import", "type": "LITERAL", "children": [{"name": "file_path",
"type": "QUOTABLE_TEXT", "children": [{"name": "--auto-meta", "type": "TEXT", "children": []}, {"name": "--meta-override", "type": "LITERAL", "children": [{"name":
"meta_override", "type": "TEXT", "children": []}]}, {"name": "backup_format", "type": "ENUMERATION", "children": [{"name": "--auto-meta", "type": "TEXT", "children"
: []}, {"name": "--meta-override", "type": "LITERAL", "children": [{"name": "meta_override", "type": "TEXT", "children": []}]}]}]}]}, {"name": "list", "type": "LITE
RAL", "children": [{"name": "--per-page", "type": "LITERAL", "children": [{"name": "per_page", "type": "INTEGER", "children": []}]}, {"name": "--creator", "type": "
LITERAL", "children": [{"name": "creator", "type": "QUOTABLE_TEXT", "children": []}]}, {"name": "--from", "type": "LITERAL", "children": [{"name": "start_date", "ty
pe": "TEXT", "children": []}]}, {"name": "--to", "type": "LITERAL", "children": [{"name": "end_date", "type": "TEXT", "children": []}]}, {"name": "-a", "type": "TEX
T", "children": []}, {"name": "--all", "type": "TEXT", "children": []}, {"name": "--flag", "type": "TEXT", "children": []}, {"name": "--flags", "type": "TEXT", "chi
ldren": []}, {"name": "page", "type": "INTEGER", "children": []}]}, {"name": "tag", "type": "LITERAL", "children": [{"name": "backup_id", "type": "INTEGER", "childr
en": [{"name": "hidden", "type": "LITERAL", "children": [{"name": "set", "type": "LITERAL", "children": [{"name": "value", "type": "BOOLEAN", "children": []}]}, {"n
ame": "clear", "type": "LITERAL", "children": []}]}, {"name": "temporary", "type": "LITERAL", "children": [{"name": "set", "type": "LITERAL", "children": [{"name":
"value", "type": "BOOLEAN", "children": []}]}, {"name": "clear", "type": "LITERAL", "children": []}]}, {"name": "protected", "type": "LITERAL", "children": [{"name"
: "set", "type": "LITERAL", "children": [{"name": "value", "type": "BOOLEAN", "children": []}]}, {"name": "clear", "type": "LITERAL", "children": []}]}]}]}]}]}<--[H
ERE]
[Server] [17:41:06] [Netty Server IO #1/INFO]: Mixing server.MixinServerboundChatCommandPacket from mixins/common/nochatreports.mixins.json into net.minecraft.class
_7472
[Server] [17:41:06] [Netty Server IO #1/INFO]: Mixing server.MixinServerboundChatPacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_2797
[Server] [17:41:06] [Netty Server IO #1/INFO]: Mixing server.MixinServerboundChatSessionUpdatePacket from mixins/common/nochatreports.mixins.json into net.minecraft
.class_7861

## Additional context丨附加信息
版本：1.20.1fabric
客户端已安装mod
在重载指令时会显示以上log

**Comment by AnzhiZhang** [comment]
请列出显示模组列表的日志

**Comment by mcxiaochenn** [comment]
这个不是吗，我reloadall只有这段报错和pb，就加了pb和mcr
---- 回复的原邮件 ----
发件人 Andy ***@***.***> 日期 2024年07月24日 18:39 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [AnzhiZhang/MCDReforgedPlugins] [Minecraft Command Register]: 指令注册失败Unknown or incomplete command, see below for error (Issue #212) 
请列出显示模组列表的日志

**Comment by AnzhiZhang** [comment]
请列出显示模组列表的日志

**Comment by AnzhiZhang** [comment]
用户使用问题，只能判断为未安装相关模组
