### ISSUE TITLE
[QQBridge]:加入了QQBridge后新人进群需要连接指定服务器才能使用/bound命令 

### ISSUE THREAD

**Issue by Redappleyyds** [AnzhiZhang/MCDReforgedPlugins#219]
### Plugin Name | 插件名

QQBridge

### Description | 描述

我有两个服务器 一个创造服 一个生存服 以上两个服务器都装了QQChat和QQAPI 这两个服务器通过QQBridge连接

### Screenshots丨截图

![image](https://github.com/user-attachments/assets/48902ab1-a399-4938-9d47-4fcdf8296a14)

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by Aimerny** [comment]
请给出更加详细的问题描述以及期望得到的结果

**Comment by AnzhiZhang** [comment]
WAI，绑定是绑定到服务器的，必须先指定

**Comment by Redappleyyds** [comment]
我想让新人执行/bound指令之后自动在两个服务器上执行/bound指令

**Comment by AnzhiZhang** [comment]
如果开启了多服务器功能，所有指令需要先指定应用的服务器，或可以关闭多服务器功能
https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/master/src/qq_chat/readme.md

**Comment by AnzhiZhang** [comment]
该功能已经在未来的更新计划中，下次请先搜索再发 issue
https://github.com/AnzhiZhang/MCDReforgedPlugins/issues/138#issue-1783854607
