### ISSUE TITLE
Bot can't spawn bot

### ISSUE THREAD

**Issue by fattoolman** [AnzhiZhang/MCDReforgedPlugins#229]
### Plugin Name | 插件名

Bot-v1.2.3

## 問題敘述
使用  **!!bot spawn**  指令時，無法成功

## Log
- 片段
  - https://mclo.gs/WfUxZGd
- 完整
  - https://mclo.gs/DFPP9fz
  
 ## Datapack
 - FZ Survival Data Pack v3.1.9-beta.3 MC1.20-1.20.6

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by AnzhiZhang** [comment]
Fallen-Breath/MinecraftDataAPI#13
