### ISSUE TITLE
[QQChat]: Is QQChat no longer supported?

### ISSUE THREAD

**Issue by Fidelxyz** [AnzhiZhang/MCDReforgedPlugins#23]
After you removed QQChat from your repo, I've looked for alternatives for it. However, ChatBridge is to huge for me (both client and server needed) and other plugins that link QQ to the game don't support automatic forwarding (though it isn't difficult to implement).

So is QQChat no longer supported? Or are there any alternatives in development?

**Comment by zhang-anzhi** [comment]
QQChat is now in [Archive](https://github.com/zhang-anzhi/MCDReforgedPlugins/tree/master/Archive) folder in my repo. It will not keep development, but it is support MCDR 2.0. [CoolQAPI](https://github.com/zhang-anzhi/CoolQAPI) will keep supported on MCDR 2.0. A project on BC server [ChatHub](https://github.com/CreatioStudio/ChatHub) will inherit all features of QQChat. But if there are stll obvious needs of QQChat, I may keep support it.

**Comment by Fidelxyz** [comment]
Thanks!

However, when I updated MCDR to 2.1.3, QQChat doesn't seem to work.

```
 [MCDR] [15:46:03] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=qq_chat@0.0.3,priority=1000,callback=<function on_load at 0x7fb9b48971e0>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mcdreforged/plugin/plugin_manager.py", line 474, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.6/site-packages/mcdreforged/plugin/plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins/QQChat.py", line 63, in on_load
    from ConfigAPI import Config
ModuleNotFoundError: No module named 'ConfigAPI'
```

That's maybe because MCDR 2.x [doesn't allow importing libs from `plugin/` directory](https://mcdreforged.readthedocs.io/en/latest/migrate/1.x_to_2.x.html#modules):

> Due to how MCDR 2.x plugin loading logic works, you can no longer places your external libs modules into your plugin/ folder and import them, since MCDR will not append the plugin folders into sys.path any more

Emmm, it seems that QQChat needs to be changed into Multi file Plugin in order to support MCDR 2.x. But it's not a big problem because I may be able to edit it for my own use.

**Comment by zhang-anzhi** [comment]
OK, I will keep QQChat support, the update will be come soon to support MCDR 2.0

**Comment by lb-chc** [comment]
（只是借用，之后删掉吧）
（刚要发你就锁定了它）

我想说：虽然我还不理解你的意思（你说的有点神秘），但谢谢你提醒我。

**Comment by AnzhiZhang** [comment]
插件加载方式有变，与 close #23 合并处理

**Comment by AnzhiZhang** [comment]
首先恭喜一下一周年，其次在做了在做了

**Comment by AnzhiZhang** [comment]
@Fidelxyz 是否还有需求？没有需求我想摆烂了，代码压根就看不懂

**Comment by AnzhiZhang** [comment]
`CoolQAPI` has been renamed to `QQAPI`. [QQAPI](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/.archived/qq_api) and [QQChat](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/.archived/qq_api) are archived at following links. Accept pull requests for maintenance or upgrade.

`CoolQAPI` 已更名为 `QQAPI`。[QQAPI](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/.archived/qq_api) 与 [QQChat](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/.archived/qq_chat) 已在下列链接归档。接受 PR 以维护更新。

<https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/.archived/qq_api>
<https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/.archived/qq_chat>

**Comment by AnzhiZhang** [comment]
@Fidelxyz Is is not supports MCDR 2.0, please find and try the plugin!
