### ISSUE TITLE
[Info] 少数特殊的主机设备运行!!info查看信息时报错

### ISSUE THREAD

**Issue by Mooling0602** [AnzhiZhang/MCDReforgedPlugins#241]
### Plugin Name | 插件名

Info

### Description | 描述

在一台armv8设备（小米平板5，安装了Ubuntu 24.04.1 LTS）上运行MCDR和服务器，执行!!info时发生报错如截图所示，插件不返回任何有效信息。

### Screenshots丨截图

![image](https://github.com/user-attachments/assets/9ccee807-3004-45f1-a502-423039f3f470)

### Additional Information | 附加信息

并非所有的arm设备都会出现这种情况，因此我暂时无法确定是主机的问题还是配置的Python环境的问题。
后续排查的相关日志如下：
```bash
mooling@xiaomi-nabu:~$ python3
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cpuinfo
>>> print(cpuinfo.get_cpu_info()['brand_raw'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'brand_raw'
>>> print(cpuinfo.get_cpu_info())
{'python_version': '3.12.3.final.0 (64 bit)', 'cpuinfo_version': [9, 0, 0], 'cpuinfo_version_string': '9.0.0', 'arch': 'ARM_8', 'bits': 64, 'count': 8, 'arch_string_raw': 'aarch64', 'flags': ['aes', 'asimd', 'asimddp', 'asimdhp', 'asimdrdm', 'atomics', 'cpuid', 'crc32', 'dcpop', 'evtstrm', 'fp', 'fphp', 'lrcpc', 'pmull', 'sha1', 'sha2']}
>>> 
```

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by AnzhiZhang** [comment]
请尝试新版，解决后麻烦帮忙发一个截图，供未来用户参考

**Comment by Mooling0602** [comment]
> 请尝试新版，解决后麻烦帮忙发一个截图，供未来用户参考

![image](https://github.com/user-attachments/assets/f15d2c86-6157-4a93-9180-dbecf6ab84a9)
