### ISSUE TITLE
[gamemode] 玩家切换旁观后立即退出服务器无法切换生存

### ISSUE THREAD

**Issue by liujinhui11** [AnzhiZhang/MCDReforgedPlugins#252]
### Plugin Name | 插件名

gamemode

### Description | 描述

生存玩家输入!s切换为旁观模式后立即退出服务器，再次进入后无法通过!s切换为生存

复现:利用Quick Menu mod ,增加如下命令
![image](https://github.com/user-attachments/assets/47955c4a-925a-4efd-9bb5-f76bca9eba99)
 点击运行后就能复现（需要有权限踢人）

 MCDR与gamemode均为最新版本
minecraft版本为 fabric-server-mc.1.20.1-loader.0.16.9-launcher.1.0.1 ,未增加模组
系统:Windows 11 22631.4460
Java版本:Java 21.0.4
Python版本:3.11.7
已加载插件:
![image](https://github.com/user-attachments/assets/e731fe15-1f14-4cf7-88b2-6c22c82c88b5)

### Screenshots丨截图

![image](https://github.com/user-attachments/assets/8e79bc27-d330-42d8-8a92-161c4181c335)
![image](https://github.com/user-attachments/assets/9216310b-eb23-42db-8e95-582097fd30c0)
![image](https://github.com/user-attachments/assets/bb1aefe0-daaf-49fc-aec5-e9d80f15c99c)

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by AnzhiZhang** [comment]
玩家退出导致 minecraft_data_api 超时，与 gamemode 无关

**Comment by liujinhui11** [comment]
如果先获取位置信息，是不是就不会出现这种情况了呢？
先获取的位置信息如果是none，那么维度就不能正常获取，也就不会保存进data
如果先获取维度，后获取坐标，那么如果在位置维度正常获取，但位置信息是返回的是none，也会正常保存进data

**Comment by AnzhiZhang** [comment]
你直接退了，上哪去获取？minecraft_data_api 是需要时间的。

该插件也不对此类非正常情况提供保证，没有正常应用场景。

**Comment by Redapple-one** [comment]
请问如何修复此bug 我服一直有一个人无法使用!s 报的也是相同的错

**Comment by liujinhui11** [comment]
在sur_to_spec函数保存玩家位置信息前判断一下是否为None应该就可以解决，像这样
`def sur_to_spec(server, player):
    dim = DIMENSIONS[minecraft_data_api.get_player_info(player, 'Dimension')]
    pos = minecraft_data_api.get_player_info(player, 'Pos')
    if (pos == None or dim == None):
        return
    data[player] = {
        'dim': dim,
        'pos': pos,
        'time': time.time(),
        'back': {
            'dim': dim,
            'pos': pos
        }
    }
    server.execute(f'gamemode spectator {player}')
    save_data(server)`

**Comment by liujinhui11** [comment]
> 请问如何修复此bug 我服一直有一个人无法使用!s 报的也是相同的错

在sur_to_spec函数保存玩家位置信息前判断一下是否为None应该就可以解决，像这样
```python
def sur_to_spec(server, player):
    dim = DIMENSIONS[minecraft_data_api.get_player_info(player, 'Dimension')]
    pos = minecraft_data_api.get_player_info(player, 'Pos')
    if (pos == None or dim == None):
        return
    data[player] = {
        'dim': dim,
        'pos': pos,
        'time': time.time(),
        'back': {
            'dim': dim,
            'pos': pos
        }
    }
    server.execute(f'gamemode spectator {player}')
    save_data(server)
```

**Comment by Redapple-one** [comment]
> > 请问如何修复此bug 我服一直有一个人无法使用!s 报的也是相同的错
> 
> 在sur_to_spec函数保存玩家位置信息前判断一下是否为None应该就可以解决，像这样
> 
> def sur_to_spec(server, player):
>     dim = DIMENSIONS[minecraft_data_api.get_player_info(player, 'Dimension')]
>     pos = minecraft_data_api.get_player_info(player, 'Pos')
>     if (pos == None or dim == None):
>         return
>     data[player] = {
>         'dim': dim,
>         'pos': pos,
>         'time': time.time(),
>         'back': {
>             'dim': dim,
>             'pos': pos
>         }
>     }
>     server.execute(f'gamemode spectator {player}')
>     save_data(server)

很高兴看到您的回复
但是

![Image](https://github.com/user-attachments/assets/909d80fa-b951-479e-9545-07e3226822e5)

**Comment by liujinhui11** [comment]
> > > 请问如何修复此bug 我服一直有一个人无法使用! s 报的也是相同的错
> > 
> > 
> > 在sur_to_spec函数保存玩家位置信息前判断一下是否为None应该就可以解决，像这样
> > def sur_to_spec（server， player）： dim = DIMENSIONS[minecraft_data_api.get_player_info（player， 'Dimension'）] pos = minecraft_data_api.get_player_info（player， 'Pos'） if （pos == None or dim == None）： return data[player] = { 'dim'： dim， 'pos'： pos， 'time'： time.time（）， 'back'： { 'dim'： dim， 'pos'： pos } }server.execute（f'GameMode 旁观者 {player}'） save_data（服务器）
> 
> 很高兴看到您的回复 但是
> 
> ![Image](https://github.com/user-attachments/assets/909d80fa-b951-479e-9545-07e3226822e5)

这种情况可以先让其他人切回生存，删除这个插件的配置文件并重载插件，之后用gamemode将他切为生存应该就可以了

**Comment by AnzhiZhang** [comment]
> 在sur_to_spec函数保存玩家位置信息前判断一下是否为None应该就可以解决，像这样

插件假设这种情况不会发生，这类切换后立即退出，没有正常的应用场景
