### ISSUE TITLE
 No module named 'ConfigAPI'

### ISSUE THREAD

**Issue by edge233** [AnzhiZhang/MCDReforgedPlugins#31]
![image](https://user-images.githubusercontent.com/60431517/169730310-fad06a9a-e5a5-429a-a223-d12a6b3823de.png)
![image](https://user-images.githubusercontent.com/60431517/169730333-08f397c6-880b-4bd5-b9a5-ba0614db19bc.png)

**Comment by AnzhiZhang** [comment]
[SinglePlayerSleep](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/Archive/SinglePlayerSleep) is archived and no longer supported, you can download [ConfigAPI](https://github.com/MCDReforged/ConfigAPI) and try fix it by your self.
