### ISSUE TITLE
[Advanced Calculator]: Some Bugs

### ISSUE THREAD

**Issue by Airero** [AnzhiZhang/MCDReforgedPlugins#55]
### (3) 异常抛出 ->TypeError，如`!!calc item []`  or  `!!calc item chr(32)`

**Comment by AnzhiZhang** [comment]
> (1) 运算 -> 复杂运算，如=2**2**2**2**2**2**2**2**2**2 or !!calc 2**2**2**2**2**2**2**2**2**2 的指令大量执行会阻塞线程

性能不足，不是插件问题

> (2) 合法性校验 ->非无符号整型，如!!calc item -1 or !!calc item 3.3

预期行为

> (3) 异常抛出 ->TypeError，如!!calc item [] or !!calc item chr(32)

已在 #54 中修复

**Comment by Airero** [comment]
还有!!calc item 2==2呢

**Comment by Airero** [comment]
我表达错了，!!calc item -1不是不应该被执行吗

**Comment by Airero** [comment]
> > (1) 运算 -> 复杂运算，如 `=2**2**2**2**2**2**2**2**2**2` or `!!calc 2**2**2**2**2**2**2**2**2**2` 的指令大量执行会阻塞线程
> 
> 性能不足，不是插件问题
> 
> > (2) 合法性校验 ->非无符号整型，如!!calc item -1 or !!calc item 3.3
> 
> 预期行为
> 
> > (3) 异常抛出 ->TypeError，如!!calc item [] or !!calc item chr(32)
> 
> 已在 #54 中修复

我表达错了，!!calc item -1不是不应该被执行吗

**Comment by AnzhiZhang** [comment]
1 无法实现限制，不能预先判断计算消耗的性能

2 不是正常是使用方式，不做限制，使用后果不保证运算准确性

**Comment by Airero** [comment]
> 1 无法实现限制，不能预先判断计算消耗的性能
> 
> 2 不是正常是使用方式，不做限制，使用后果不保证运算准确性

好吧

**Comment by AnzhiZhang** [comment]
第一个问题目前最新版已修复
