### ISSUE TITLE
[bot]: index 的页码列表在哪，没找到，假人动作用不了

### ISSUE THREAD

**Issue by itooken** [AnzhiZhang/MCDReforgedPlugins#61]
## Describe
A clear and concise description of your issue.

## Details
Some details for your issue.

**Comment by itooken** [comment]
index的页码列表在哪，没看到哇，假人动作要整数，但是我不知道哇

**Comment by AnzhiZhang** [comment]
I need "A clear and concise description of your issue" please.

**Comment by itooken** [comment]
!!bot action [index] 执行假人动作
我输入!!bot action <name> use用不了，说是要什么整数，请问执行假人动作应该怎么输呢

**Comment by itooken** [comment]
index列表的页码，请问这个啥意思，不是很懂

**Comment by AnzhiZhang** [comment]
这个index是动作列表的index，例如储存了五个动作，`!!bot action <name>` 即为执行全部五个动作，若指定 `index` 即为仅执行该动作

**Comment by itooken** [comment]
感谢解答
