### ISSUE TITLE
[Gamemode]: 重载/重启服务器后会使玩家保存的状态失效

### ISSUE THREAD

**Issue by charassss** [AnzhiZhang/MCDReforgedPlugins#68]
## Describe
可以使玩家在某些条件下完成远距离传送

## Details
玩家使用!!spec指令后，若重载插件后，玩家再次!!spec会使玩家再一次进入到观察者，并刷新观察上线位置。在此之前移动到想要的位置并输入两次!!spec就可以传送到该位置

## Expected behavior
在重载插件后保留玩家的旁观、位置数据

**Comment by AnzhiZhang** [comment]
看了下代码，数据是存储到文件中的，插件重载会重新从文件中读取数据，是否有关于文件读写的报错信息？

**Comment by charassss** [comment]
```bash
[MCDR] [21:12:53] [TaskExecutor/INFO]: 正在重载插件 gamemode@0.1.0
[MCDR] [21:12:54] [TaskExecutor/INFO]: 插件 gamemode@0.1.0 已重载
[MCDR] [21:12:54] [TaskExecutor/INFO] [gamemode]: 配置文件已加载
[MCDR] [21:12:54] [TaskExecutor/INFO] [gamemode]: 配置文件已加载
```
没有观察到文件读写报错信息

**Comment by charassss** [comment]
貌似是我的问题,插件在src里的最新版是0.1.1,但是我在releases只找到了0.1.0,所以以为0.1.0是最新版

**Comment by charassss** [comment]
但是貌似0.1.0也有有关于data.json的配置文件
